name: 📺 EPG Request
description: Request to add Electronic programming guide (EPG) in this repository
title: 'Add: '

body:
  - type: markdown
    attributes:
      value: |
        Please fill out the issue template as much as you can so we could efficiently process your request

  - type: input
    attributes:
      label: Channel Name
      description: Channel Name from iptv-org/database. A complete list of supported channels can be found on iptv-org.github.io.
      placeholder: 'BBC America East'
    validations:
      required: true

  - type: input
    attributes:
      label: Channel ID
      description: Unique channel ID from iptv-org/database. A complete list of supported channels can be found on iptv-org.github.io..
      placeholder: 'BBCAmericaEast.us'
    validations:
      required: true

  - type: input
    attributes:
      label: Website
      description: Website where the EPG can be found?
      placeholder: 'https://cablecompany.com/tvlisting'
    validations:
      required: true

  - type: textarea
    attributes:
      label: Notes
      description: 'Anything else that helps? API Url, Etc'