name: 📺 Channel Request
description: Request to add channels to the list
labels: ['📺 channel request']

body:
  - type: markdown
    attributes:
      value: |
        Please fill out the issue template as much as you can so we could efficiently process your request

  - type: input
    attributes:
      label: Source
      description: Website where you saw the program for the channel
      placeholder: 'https://cablecompany.com/tvlisting'
    validations:
      required: true

  - type: textarea
    attributes:
      label: Channels
      description: List all channels that need to be added
      placeholder: |
        - Channel1
        - Channel2
        ...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Notes
      description: Anything else we should know?