name: 🗓 EPG Request
description: Request to add a new EPG (Electronic Programming Guide) source to the repository
labels: ['🗓 epg request']

body:
  - type: markdown
    attributes:
      value: |
        Please fill out the issue template as much as you can so we could efficiently process your request

  - type: input
    attributes:
      label: Source
      description: Website where the EPG can be found?
      placeholder: 'https://cablecompany.com/tvlisting'
    validations:
      required: true

  - type: textarea
    attributes:
      label: Notes
      description: 'Anything else that helps? API Url, Etc'