name: 💡 Feature Request
description: For any ideas or feature requests
labels: ['💡 feature request']

body:
  - type: textarea
    attributes:
      label: Description
      description: Please describe your idea in as much detail as possible so that we can efficiently process your request
    validations:
      required: true
