name: 🐞 Bug Report
description: Report an error in this repository
labels: ['🐞 bug']

body:
  - type: markdown
    attributes:
      value: |
        Please describe the error in as much detail as possible so that we can fix it quickly.

  - type: textarea
    attributes:
      label: Description
    validations:
      required: true
