name: 🐞 Bug Report
description: Report an error in this repository
labels: ['🐞 bug']

body:
  - type: textarea
    attributes:
      label: Description
      description: Please describe the error in as much detail as possible so that we can fix it quickly.
    validations:
      required: true
