name: auto-update
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  grab:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        site:
          [
            telkussa.fi,
            andorradifusio.ad,
            znbc.co.zm,
            hd-plus.de,
            astro.com.my,
            comteco.com.bo,
            mi.tv,
            meo.pt,
            tvgid.ua,
            m.tv.sms.cz,
            cosmote.gr,
            programetv.ro,
            programtv.onet.pl,
            digiturk.com.tr,
            programme-tv.net,
            programacion-tv.elpais.com,
            guidatv.sky.it,
            ontvtonight.com,
            tv.yandex.ru,
            tvtv.ca,
            tvtv.us,
            tv.lv,
            vidio.com,
            tvguide.com,
            tvprofil.com
          ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Run EPG Grabber
        run: npx epg-grabber --config=sites/${{ matrix.site }}.config.js
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: .gh-pages
          path: .gh-pages/guides/${{ matrix.site }}.guide.xml
  deploy:
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: grab
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Artifacts
        uses: actions/download-artifact@v2
      - name: Generate Token
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: .gh-pages
          target-folder: guides
          clean: false
          token: ${{ steps.generate-token.outputs.token }}
          git-config-name: iptv-bot
          git-config-email: 84861620+iptv-bot[bot]@users.noreply.github.com
          commit-message: '[Bot] Deploy to GitHub Pages'
