name: auto-update
on:
  workflow_dispatch:
jobs:
  update-guide:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update Guide
        run: ./run.sh
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.REPO_SCOPED_TOKEN }}
          BASE_BRANCH: master
          BRANCH: gh-pages
          FOLDER: .gh-pages
