name: auto-update
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        if: ${{ !env.ACT }}
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm install
      - run: node scripts/commands/create-database.js
      - run: node scripts/commands/create-matrix.js
        id: create-matrix
      - uses: actions/upload-artifact@v2
        with:
          name: database
          path: scripts/database
    outputs:
      matrix: ${{ steps.create-matrix.outputs.matrix }}
  load:
    runs-on: ubuntu-latest
    needs: setup
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.setup.outputs.matrix) }}
      # matrix:
      #   cluster_id: [1]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: database
          path: scripts/database
      - uses: FedericoCarboni/setup-ffmpeg@v1
      - uses: actions/setup-node@v2
        if: ${{ !env.ACT }}
        with:
          node-version: '14'
      - run: npm install
      - run: NODE_OPTIONS=--insecure-http-parser node scripts/commands/load-cluster.js --days=2 --timeout=30000 --cluster-id=${{ matrix.cluster_id }}
      - uses: actions/upload-artifact@v2
        with:
          name: logs
          path: scripts/logs
  update:
    runs-on: ubuntu-latest
    needs: load
    steps:
      - uses: actions/checkout@v2
      - run: echo "::set-output name=branch_name::$(date +'bot/auto-update-%s')"
        id: create-branch-name
      - run: git config user.name 'iptv-bot[bot]'
      - run: git config user.email '84861620+iptv-bot[bot]@users.noreply.github.com'
      - run: git checkout -b ${{ steps.create-branch-name.outputs.branch_name }}
      - run: curl -L -o scripts/data/codes.json https://iptv-org.github.io/epg/codes.json
      - uses: actions/download-artifact@v2
        with:
          name: database
          path: scripts/database
      - uses: actions/download-artifact@v2
        with:
          name: logs
          path: scripts/logs
      - uses: actions/setup-node@v2
        if: ${{ !env.ACT }}
        with:
          node-version: '14'
      - run: npm install
      - run: node scripts/commands/save-results.js
      - uses: actions/upload-artifact@v2
        with:
          name: database
          path: scripts/database
      - run: NODE_OPTIONS="--max-old-space-size=4096" node scripts/commands/update-api.js
      - run: NODE_OPTIONS="--max-old-space-size=4096" node scripts/commands/update-guides.js
      - uses: actions/upload-artifact@v2
        with:
          name: logs
          path: scripts/logs
      - uses: actions/upload-artifact@v2
        with:
          name: channels.json
          path: .gh-pages/api/channels.json
      - uses: actions/upload-artifact@v2
        with:
          name: programs.json
          path: .gh-pages/api/programs.json
      - uses: actions/upload-artifact@v2
        with:
          name: guides
          path: .gh-pages/guides
      - run: node scripts/commands/update-readme.js
      - run: git add README.md
      - run: git commit -m "[Bot] Update README.md"
      - run: git push -u origin ${{ steps.create-branch-name.outputs.branch_name }}
      - uses: tibdex/github-app-token@v1
        if: ${{ !env.ACT }}
        id: create-app-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: repo-sync/pull-request@v2
        if: ${{ !env.ACT }}
        id: pull-request
        with:
          github_token: ${{ steps.create-app-token.outputs.token }}
          source_branch: ${{ steps.create-branch-name.outputs.branch_name }}
          destination_branch: 'master'
          pr_title: '[Bot] Daily update'
          pr_body: |
            This pull request is created by [auto-update][1] workflow.

            [1]: https://github.com/iptv-org/epg/actions/runs/${{ github.run_id }}
      - uses: juliangruber/merge-pull-request-action@v1
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github-token: ${{ secrets.PAT }}
          number: ${{ steps.pull-request.outputs.pr_number }}
          method: squash
      - uses: JamesIves/github-pages-deploy-action@4.1.1
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          branch: gh-pages
          folder: .gh-pages
          token: ${{ steps.create-app-token.outputs.token }}
          git-config-name: iptv-bot[bot]
          git-config-email: 84861620+iptv-bot[bot]@users.noreply.github.com
          commit-message: '[Bot] Deploy to GitHub Pages'
