name: auto-update
on:
  workflow_dispatch:
jobs:
  update-guide:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update Guide
        run: ./run.sh
      - name: Commit Changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git diff-index --quiet HEAD || git commit -m "[Bot] Update Guide"
          git pull
          git push
