name: EPG Generator Workflow

on:
  workflow_dispatch:

jobs:
  generate_channels_list:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm ci

    - name: Generate Custom Channel List
      run: npm run channels:generate

    - name: Run EPG grabber
      run: npm run grab

    - name: Commit custom channel list (if needed)
      run: |
        git add custom_channels.xml
        git commit -m "Add custom channels list"
        git push
