name: test
on:
  workflow_dispatch:
jobs:
  grab:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        site: [hd-plus.de, andorradifusio.ad, znbc.co.zm]
      fail-fast: false
      max-parallel: 2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Run EPG Grabber
        run: npx epg-grabber --config=sites/${{ matrix.site }}.config.js
